### ISSUE TITLE
tests fail: vtkOpenGLPolyDataMapper has no attribute 'SetArrayName'

### ISSUE THREAD

**Issue by RizzerOnGitHub** [marcomusy/vtkplotter#98]
Building and testing vtkplotter2020.0.2 on Debian GNU/Linux (2020.0.2+dfsg1-1), the tests fails, e.g.

    tests/common$ ./run_all.sh 
    Processing test_actors.py script..
    Traceback (most recent call last):
      File "test_actors.py", line 11, in <module>
        cone.addCellScalars(carr, 'carr')
      File "/usr/lib/python3/dist-packages/vtkplotter/base.py", line 714, in addCellScalars
        self._mapper.SetArrayName(name)
    AttributeError: 'vtkRenderingOpenGL2Python.vtkOpenGLPolyDataMapper' object has no attribute 'SetArrayName'

Similar errors with `vtkOpenGLPolyDataMapper object has no attribute 'SetArrayName'` shows when trying to run the tests in tests/dolfin.

vtkplotter has been built against python3-vtk7.

**Comment by marcomusy** [comment]
Thanks for spotting it! I didn't think of vtk7 ...
I will make newer release soon which will address this.
